---

shell: /bin/bash

packages:
  - apt-transport-https
  - curl
  - gnupg
  - vim
  - htop
  - ca-certificates
  - python3-pip

dock_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

ubuntu_gpg: https://download.docker.com/linux/ubuntu/gpg
ubuntu_repo: https://download.docker.com/linux/ubuntu

debian_gpg: https://download.docker.com/linux/debian/gpg
debian_repo: https://download.docker.com/linux/debian
