---
- name: Create PiHole
  become_user: "{{ ansible_user }}"
  community.docker.docker_compose:
    project_name: pihole
    definition:
      services:
        pihole:
          image: pihole/pihole
          restart: always
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8076:443/tcp"
          environment:
            - TZ="{{ time_zone }}"
            - WEBPASSWORD="{{ web_password }}"
            - WEBTHEME=default-dark
            - PIHOLE_DNS_="9.9.9.9;1.1.1.1"
            - DNSSEC="true"
          volumes:
            - "{{ defualt_relative_docker_data_path }}/pihole:/etc/pihole"
            - "{{ defualt_relative_docker_data_path }}/pihole-dnsmasq.d:/etc/dnsmasq.d"
