http:
 #region routers 
  routers:    
    jackett:
      entryPoints:
        - "https"
      rule: "Host(`jackett.homelab.ezequielvalencia.com`)"
      middlewares:
        - secured
      tls: {}
      service: jackett
    
    qbit:
      entryPoints:
        - "https"
      rule: "Host(`qbit.homelab.ezequielvalencia.com`)"
      middlewares:
        - secured
      tls: {}
      service: qbit

  services:
    # Tools
    jackett:
      loadBalancer:
        servers:
          - url: "http://gluetun:9117"
        passHostHeader: true
    qbit:
      loadBalancer:
        servers:
          - url: "http://gluetun:9078"
        passHostHeader: true

#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        # - "192.168.0.0/16"
        # - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
        - https-redirectscheme