---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBFy7XLcCo693K6xamEGjr9kTVL4+j4oVLPU+jHKpNtws2/8IbSchduHXwRQIljt/bXgG/IwBAdlblLovDIfnT+FWqYQsKE6I3txGSzLgOf7HlFFb0MBHBcqP8zfg6FCMiL3a2+HcLD++JSnsGH5rUb9BzMMtzeLPV2zUvfNOwtG1d27opoMWTxM2UFh8IHhJHclvg6BDpk4zu0G9E8RHF+TUcV0E7NFUfuWF2CBZPiR4hdq7aYdCZuT040pnECaMm+meEE+P2X0fBbGL5fL08Ib4aZjO4FuaAo1C7FP7/wAwgifY7ma9rOWvFggxnzALescTyb+Ap1kMWnC2JEz86P+ca6eMwNdb6wczuom/zQ7fdKBsw9fSgh6vIUPHeuUMkrczcUsSInkqXbXETnD1TvgLMi1mfTCiK7ZDCAyqRwhzxmJGJnQlW/G+EYNqlIIrTuhvdlIMckeQl/htuEfbkhfKfSJK/8pM6UyLl69IeKojgeoSbEjLd7ODdHH2FKk686ukq6rLFSA9MdnbdCn9biIWminxpr9xo6TqwcwQOkykzoaMTdQhssr5u+KLuf58sgzK5/jx2g/lkeBLTRWhx5s+GoEGbJk51I7GXs2drfyGfsv6NABubsacReZbwQ0+DiQsbVPxPHSqKUgq3SfHfjpx35v9LM+uR9FmXCHmCPcloz8hwWMJRYB8C/8jjvSo82uA5F4HHiLiLbqYPqkL0GNZSi+VKHhr9Qmuj5dIT6vGweHdMPslBz
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
