---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: media
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAOwxkLXKFMZh77HAL1mvhh54Kuq5W0/sFPSEmqLwJkZ+pLAd2r59yKV62kgDR3IX+Iannn/93zV0OixwqZSYrTqZZRwxecZk0A47kva1Jpx5nwDDQwhwyinPYXsFInznW+Wce03X1frKttiXPC0Z+KswCDpSHKDVzJG8dUB/LLWPq6WbUwbJx7ZpTgbSkWvC4hZJiCOGtlqKsOZnlYpqEAP8GIWCjILZZmPGLL2GHQ8zPmqIDwnGKDy2TrSRZhvGObWCxjzgzuUvij6tS7iRR/pmIbG0GxDgrNwC2htRQ+5GpxiND8ZIgjaPKhkcPCgDpMUGCb38VcKmWiUy8RG49BW4hagn09EgIriKzRDbRN+QrZsupj/hdm+o2VNwq6jv4jWeOVoCl2bhRyPqb3N8tabkoxOpx+lcPvdw4MtuFrgKhp9Jm/kRyjxQkckhuTZ9VobJMbKA2+ElCRASgKQifgHw2zf8aXGsAyXVdLE6n7NpVy+2oGVw7AgQyXAnscMLPht7lSsHFhmSX+55RZdOZCi6LT7bcD8Tffv8hmo2n8Lig+K88cIm/Vjctg52NWVLAjNbZFQY8CHrNdgCteBjAbTfA6IENsRGOcTSKjPIa9QZa+Sk/TzFvkBTBbyeKE0tuiqS9GoE/ha/apWFasQeJkJsO/izVHCbj9+KfBAbn41bifoyP0bYhAJfPy3j8ROFYBfV/RCVqN3Jz1zTiorZLRSRk0abHQF3V/f7tWjZp/aNiyZ73wvmkj0Z43TBy2FHfufFMwMF72dsCN5Wfk6qtGFk7Pwnp4OXOT355n/hkD77lIPQblfrwKmiKW9yjfWFBf+nRovGBiaGijmm4+G2jjB5vIGtnykYAlc8Axm5Te7M+CBJZbTmGb60wnGTJkk8Fkj+4D2Vsy5C27r8ApTSaXZr4s14Sl8vsxfnYy+kpTA4TuRsyP+PEn
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: media
