---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgATGryeMwmvHjQFLQqPnxGLsGMEKrBhu/b9aJv6rtmsdBvVrAERTDw+VilEkRjCGqFUHs/8PZkso2YcOWrKM36TTMS4c1Cur5HxC3wpIxXMHBa/4jlgynpTjCLjxJl5zoOiHHSKz+0z8U5C9tdq6l4lV77tMhsIxddQ0tB/b4uiYyg89djSIHTouG9MdcXAa+m/2WFznp/MB+inWXP8wwilOsRMlfBfx5WmYrlqMsD/gmK9dbwfNk9j8X3dbWsZy4Yc/iC6Ufke80WNB1majrjXIlL/mYODfBqlWjYZU1dm6Hber62Q+MIuMQ22IK6uadbr7fGi+RFoY2UxxHyMIsQu63LAumUZ7OrNxUQnl4b282gTcGBrI+xS1PiFd75Gb7s/QJgU+PcZcXXs5VR3n/rTgw9N7zgDUeDCLwt2C69JjLNDzIrdZi3LB5p29/FcH3AwZy0nGfylcAGWdZ6VG8j+XNSEzueJvdOqjyjIDQj5mkJYHfXRUZGfWpuh+ykUwKlr3vZ9oJGolnJ3yNdBGp8SgkMhlLcIU0p/LbnsUBrFG0uI9r03VtLNtm4LLGxAemCDrpfxGNOeYpcNjUr9ezyjcNI0/r5uo+3xNW+kC+VkWDXiYv9V46BFMlVplgzU4u105RMYtWaLhaAqBnMvDU83aGOPY0bDQiQn/+6KmfFYrHRPj0uRqnIN5XxEVGL84WpJRuxE5vBKVO1WcFlazND6OMJy
    admin-user: AgCwONOxSFGm3EKOAewu66k0JyfujH28J1ue1MjY2t2CssIr2wBlNwLwy/IUwmzaKwY9lJy5EH/l4Qi5VABU+OVPj3VooVgt/mAbn9T9wwPQFiOgdf8gh8Bugg5b+3PDAGTWTON/6v+ANMq4XdOOvXYXhshSZeWzXXrq0f8Yta4Gx6WwF4KtM6AkY6NkvQDW1JwH21+OnqpHCXukezQ03EpyJhICF9U9sug5TuF/A4YFVCvsptejTdVvbEFS5NFKxkui45IIsdwT3/PhlWP5SgAKHJXyyUNVVVKhUw24fUxT0q2d8xO6ECStRuBCWIC9s/j0ZRvsiIKuijUIoI6h74iEWVwwIrgm7UAJX4Cw6jc9swNfjQUaT95uS45pvvztYQUr9o+rxMWFI1PD5YFQXYMXImVYttcXItm3DOfZjRVLhY4PZ+AMpjNEnmLXdjrT3wx1yDS653J5VArAX1zYQ7OeM+k7rSnoO0d9MXX77G6UThJYNtydj7p9Swh6S7fnor4hmPpY1aPUaDIL4BcKbFNSakyPnjJpC3kJtiEjYCXp/xurC4/MPD4fdSrXIYEkPc6odFizcMsMZRUBdhJy+Y3Z1L1/d1hKrIyGpuVVX7W6ewm9T4ip0cDuCqVm5UP6gS+cuzQ4UNNIniw3EGBy2cgEknBXN3c6r0keNAK1+dGUOn7GIZvFKyuL9qFJmWS/PIcmTondqA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
