apiVersion: batch/v1
kind: Job #Job instead of deployment because of it's ability to back off x num of failures
metadata:
  name: eventscraper
spec:
  template:
    spec:
      containers: 
        - name: eventscraper
          image: avocadomoon/ctevent-scraper:latest
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          envFrom:
            - secretRef:
                name: eventscraper-secrets
            - configMapRef:
                name: eventscraper-env
          resources:
            limits: 
              memory: 512M
              cpu: "300m"
          volumeMounts:
            - name: eventscraper-storage
              mountPath: /app/config
      volumes:
        - name: eventscraper-storage
          persistentVolumeClaim:
            claimName: eventscraper-storage-claim
      restartPolicy: Never
  backoffLimit: 3
