api:
  dashboard: false
  debug: false
log:
  level: INFO
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflareResolver:
    acme:
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: "60"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.