---
# https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options
# https://docs.docker.com/storage/volumes/
# https://forums.docker.com/t/is-there-a-maximum-size-for-docker-volumes/20978
# fd
# https://www.redhat.com/sysadmin/resize-lvm-simple
#  In case the volume present is to small, can create future volumes to increase its size, want to share it
#  Seems conflicted as to whether there is a storage limit though
# - name: Create docker volumes
#   community.docker.docker_volume:
#     volume_name: "{{ volume.vname }}"
#     state: present
#     recreate: never
#     driver: local
#     driver_options:
#       size: "{{ volume.size }}"
#   loop:
#     - vname: "Movies"
#       size: 300G

#     - vname: "TV"
#       size: 300G

#     - vname: "Downloads"
#       size: 50G
#   loop_control:
#     loop_var: volume

# - name: Make the space available to containers larger
#   become: true
#   community.general.lvol:
#     vg: ubuntu-vg
#     lv: ubuntu-lv
#     size: 90%FREE
#     shrink: false

##############################################
## Increase storage for overlay file system ##
##############################################
- name: Partition new disk space
  become: true
  community.general.parted:
    device: /dev/sdb
    number: "{{ parition_number }}"
    state: present
    part_end: 100%
  register: partition_result

- name: Format new partition
  become: true
  community.general.filesystem:
    fstype: "{{ file_system_type }}"
    dev: "{{ new_partition }}"

- name: Mount new partition
  become: true
  ansible.posix.mount:
    src: "{{ new_partition }}"
    path: "{{ where_to_mount_storage_device }}"
    fstype: "{{ file_system_type }}"
    state: mounted
