---

- name: Make PiHole data directory
  become: true
  ansible.builtin.file:
    path: "{{ default_relative_docker_data_path }}/pihole"
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Make PiHole dnsmasq.d directory
  become: true
  ansible.builtin.file:
    path: "{{ default_relative_docker_data_path }}/pihole-dnsmasq.d"
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Template PiHole DNS records
  become: true
  ansible.builtin.template:
    src: pihole-dns.conf.j2
    dest: "{{ default_relative_docker_data_path }}/pihole-dnsmasq.d/01-ansible-dns.conf"
    mode: u=rw,g=r,o=
  notify: Restart PiHole
