---
- name: Traefik Setup
  ansible.builtin.include_tasks: traefik-setup.yml

- name: Copy HA Configuration File
  become: true
  ansible.builtin.copy:
    mode: u=rw,g=r,o=r
    src: ha_configuration.yaml
    dest: "{{ default_relative_docker_data_path }}/home-assistant/configuration.yaml"
    backup: true

# - name: Copy Frigate Configuration File
#   become: true
#   ansible.builtin.copy:
#     mode: u=rw,g=r,o=r
#     src: frigate.yml
#     dest: "{{ default_relative_docker_data_path }}/frigate/config/config.yml"

- name: Setup Home Assistant Compose
  vars:
    docker_template_files: []
    source_compose_file: home-assistant.compose.yml
    remote_compose_file: home-assistant.compose.yml
    compose_project_name: home-assistant
  ansible.builtin.include_tasks: ../tasks/docker-compose-up.yml
