---
- name: Create event group
  become: true
  ansible.builtin.group:
    name: 'eventg'
    state: present
  register: group_return_values

- name: Create event scraper users
  become: true
  ansible.builtin.user:
    name: "{{ current_user.name }}"
    uid: "{{ current_user.PUID }}"
    groups: "{{ group_return_values.name }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: current_user
