---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "casualcucumber59@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: "ezequiel7835@gmail.com"
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "example.com"

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "casualcucumber59@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: "ezequiel7835@gmail.com"
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "ezequielvalencia.com"


---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-certificate
  namespace: media
spec:
  secretName: media-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.homelab.ezequielvalencia.com"
  dnsNames:
  - "jellyfin.homelab.ezequielvalencia.com"
  - "bazarr.homelab.ezequielvalencia.com"
  - "radarr.homelab.ezequielvalencia.com"
  - "sonarr.homelab.ezequielvalencia.com"
  - "jackett.homelab.ezequielvalencia.com"
  - "qbit.homelab.ezequielvalencia.com"
  - "lidarr.homelab.ezequielvalencia.com"
