http:
 #region routers 
  routers:
    # Tools
    
    nextcloud:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.homelab.ezequielvalencia.com`)"
      middlewares:
        - default-headers
      tls: 
        certResolver: cloudflareResolver
      service: nextcloud

    uptime:
      entryPoints:
        - "https"
      rule: "Host(`uptime-kuma.homelab.ezequielvalencia.com`)"
      middlewares:
        - default-headers
      tls: 
        certResolver: cloudflareResolver
      service: uptime
    

#endregion
#region services
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud.docker"
        passHostHeader: true
    uptime:
      loadBalancer:
        servers:
          - url: "http://uptime.docker:3001"
        passHostHeader: true
    

#endregion
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
        - default-headers