---
- name: Update this
  ansible.builtin.include_tasks:
    update.ansible.yml

- name: Install Dock
  ansible.builtin.include_tasks:
    install_docker.ansible.yml

- name: SSH
  ansible.builtin.include_tasks:
    ssh.ansible.yml
