---

where_to_mount_storage_device: /mnt/overlay2
mounted_path: "{{ where_to_mount_storage_device }}{{ defualt_relative_docker_data_path }}"


parition_number: 1
new_partition: /dev/sdb{{ parition_number }} # !!! DANGEROUS CONSTANT !!! # dont want name conflictions
file_system_type: ext4


users:
  - name: servarr
    PUID: 1015

  - name: tors
    PUID: 1006
  
  - name: jellyfin
    PUID: 1016

