---

shell: /bin/bash

packages:
  - apt-transport-https
  - curl
  - gnupg
  - vim
  - htop
  - ca-certificates

dock_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
