---

- name: Copy env files to container
  ansible.builtin.template:
    mode: u=rw,g=r
    src: "{{ item.src }}"
    dest: "~/{{ item.name }}"
  loop: '{{ traefik_template_files }}'

- name: Make Docker Volume Directory
  become: true
  ansible.builtin.file:
    mode: u=rwx,g=rwx,o=
    path: "{{ defualt_relative_docker_data_path }}"
    state: directory

- name: Make Traefik user
  become: true
  ansible.builtin.user:
    name: '{{ traefik_local_user }}'

- name: Make Traefik directory
  become: true
  ansible.builtin.file:
    mode: u=rwx,g=rwx,o=
    path: "{{ defualt_relative_docker_data_path }}/traefik"
    state: directory
    owner: "{{ traefik_local_user }}"

- name: Copy traefik config files
  become: true
  ansible.builtin.copy:
    mode: u=rw,g=r,o=
    src: "{{ item }}"
    dest: "{{ defualt_relative_docker_data_path }}/traefik/{{ item }}"
    owner: "{{ traefik_local_user }}"
  loop: '{{ traefik_files }}'

- name: Make ACME json file
  become: true
  ansible.builtin.file:
    mode: u=rw,g=,o=
    path: "{{ defualt_relative_docker_data_path }}/traefik/acme.json"
    state: touch
    owner: "{{ traefik_local_user }}"

- name: Create Traefik
  community.docker.docker_compose:
    project_name: Traefik
    project_src: "~/"
    files:
      - "traefik.compose"

- name: Delete env files
  ansible.builtin.file:
    path: "~/{{ item.name }}"
    state: absent
  loop: '{{ traefik_template_files }}'
