---
- name: Init VM Nodes for K8
  hosts: k3s_cluster
  gather_facts: false
  vars:
    other_port: true
    alt_ssh_port: 5320

  pre_tasks:
    - name: Get facts after SSH set
      ansible.builtin.include_tasks: ../tasks/gather-facts-ssh.yml

    - name: Change Python Env
      ansible.builtin.include_tasks: ../tasks/change-python-env.yml

  roles:
    - debian-system-startup

- name: Init Media Node for K8
  hosts: media
  gather_facts: false
  vars:
    other_port: true
    alt_ssh_port: 5320

  pre_tasks:
    - name: Get facts after SSH set
      ansible.builtin.include_tasks: ../../tasks/gather-facts-ssh.yml

    - name: Change Python Env
      ansible.builtin.include_tasks: ../../tasks/change-python-env.yml

    - name: Include Media Secrets
      ansible.builtin.include_vars: ../../inventory/secrets/media.secrets.yml

  roles:
    - media_install
