---
- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install essential packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present

- name: Install python requirements
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name:
      - requests
      - docker
      - docker-compose
