--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventscraper-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  hostPath:
    path: /docker_data/eventscraper
    type: DirectoryOrCreate


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventscraper-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 10Gi
  volumeName: eventscraper-storage

