---
media_path_tv: "{{ defualt_relative_docker_data_path }}/media/tv"
media_path_movies: "{{ defualt_relative_docker_data_path }}/media/movies"
media_path_books: "{{ defualt_relative_docker_data_path }}/media/books"
media_path_music: "{{ defualt_relative_docker_data_path }}/media/music"
media_path_downloads: "{{ defualt_relative_docker_data_path }}/media/downloads"


container_name: gluetun

unified_network: "container:{{ container_name }}"

media_PGID: 1002

media_UMASK: 002

users:
  - name: jelly-arr
    PUID: 1005

  - name: tors
    PUID: 1006
