---
media_path_tv: "{{ defualt_relative_docker_data_path }}/media/tv"
media_path_movies: "{{ defualt_relative_docker_data_path }}/media/movies"
media_path_books: "{{ defualt_relative_docker_data_path }}/media/books"
media_path_music: "{{ defualt_relative_docker_data_path }}/media/music"
media_path_downloads: "{{ defualt_relative_docker_data_path }}/media/downloads"

# Needed since applications communicate giving paths within their own systems since
# they believe they are communicating in the same machine
internal_downloads: "/media/downloads"
internal_movies: "/media/movies"
internal_tv: "/media/tv"
internal_books: "/media/books"
internal_music: "/media/music"

jellyfin_config_path: "{{ defualt_relative_docker_data_path }}/config/jellyfin"
qbit_config_path: "{{ defualt_relative_docker_data_path }}/config/qbittorent"
jackett_config_path: "{{ defualt_relative_docker_data_path }}/config/jackett"
bazarr_config_path: "{{ defualt_relative_docker_data_path }}/config/bazarr"
radarr_config_path: "{{ defualt_relative_docker_data_path }}/config/radarr"
sonarr_config_path: "{{ defualt_relative_docker_data_path }}/config/sonarr"
gluetun_config_path: "{{ defualt_relative_docker_data_path }}/config/gluetun"


container_name: gluetun

unified_network: "container:{{ container_name }}"

media_UMASK: 002

users:
  - name: jelly-arr
    PUID: 1005

  - name: tors
    PUID: 1006
