- name: Create PiHole
  community.docker.docker_container:
    name: PiHole
    image: pihole/pihole
    state: started
    restart_policy: always
    recreate: true
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8076:443/tcp"
    dns_opts:
      - "9.9.9.9"
      - "1.1.1.1"
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ web_password }}"
      WEBTHEME: "default-dark"
      PIHOLE_DNS_: "9.9.9.9;1.1.1.1"
      DNSSEC: "true"
    volumes:
      - "{{ defualt_relative_docker_data_path }}/pihole:/etc/pihole"
      - "{{ defualt_relative_docker_data_path }}/pihole-dnsmasq.d:/etc/dnsmasq.d"
