- name: Create PiHole
  community.docker.docker_container:
    name: PiHole
    image: pihole/pihole
    state: started
    restart_policy: always
    recreate: true
    published_ports:
      - "53:53/tcp"
      - "8076:443/tcp"
    dns_opts:
      - "9.9.9.9"
      - "1.1.1.1"
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ web_password }}"
      WEBTHEME: "default-dark"
      PIHOLE_DNS_: "9.9.9.9;1.1.1.1"
      DNSSEC: "true"

# https://github.com/pi-hole/docker-pi-hole#readme

# - name: Install Traefik
#   community.docker.docker_container:
#     name: Traefik
#     image: traefik
