apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediavpn
  name: mediavpn
spec:
  selector:
    matchLabels:
      app: mediavpn
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediavpn
    spec:
      # https://www.ibm.com/docs/de/spectrum-conductor/2.5.0?topic=instances-network-provisioning-docker-pods
      # https://stackoverflow.com/questions/49368047/what-is-the-equivalent-for-depends-on-in-kubernetes
      
      # Sidecar container because of restart policy
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: vpn-secrets
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities: 
              add: ["NET_ADMIN"] # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
          resources:
            limits: 
              memory: 512M # 0.5GB Memory
              cpu: 500m # 0.5CPU core
          restartPolicy: Always
          ports:
            - containerPort: 6767
            - containerPort: 8989
            - containerPort: 7878
            - containerPort: 9117
            - containerPort: 8686
            - containerPort: 9078
            - containerPort: 6881
          volumeMounts:
            - name: media-config-local-storage
              mountPath: /gluetun
              subPath: gluetun
          # healthcheck: # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/        
      
      containers: 
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: arr-user
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits: 
              memory: 512M
              cpu: 500m
          volumeMounts:
            - name: media-local-storage
              mountPath: /media/tv
              subPath: tv
            - name: media-local-storage
              mountPath: /media/downloads
              subPath: downloads
            - name: media-config-local-storage
              mountPath: /config
              subPath: sonarr

        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: arr-user
          resources:
            limits: 
              memory: 512M
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: media-local-storage
              mountPath: /media/movies
              subPath: movies
            - name: media-local-storage
              mountPath: /media/downloads
              subPath: downloads
            - name: media-config-local-storage
              mountPath: /config
              subPath: radarr

        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: arr-user
          resources:
            limits: 
              memory: 512M
              cpu: 250m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: media-local-storage
              mountPath: /media/tv
              subPath: tv
            - name: media-local-storage
              mountPath: /media/movie
              subPath: movie
            - name: media-config-local-storage
              mountPath: /config
              subPath: bazarr
        
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          imagePullPolicy: Always
          env:
            - name: AUTO_UPDATE
              value: 'true'
          resources:
            limits: 
              memory: 512M
              cpu: 250m
          envFrom:
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: torrent-user
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: media-config-local-storage
              mountPath: /config
              subPath: jackett
        
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: WEBUI_PORT
              value: '9078'
          resources:
            limits: 
              memory: 512M
              cpu: 500m
          envFrom:
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: torrent-user
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - name: media-config-local-storage
              mountPath: /config
              subPath: qbittorent
            - name: media-local-storage
              mountPath: /media/downloads
              subPath: downloads
      
      volumes:
        - name: media-config-local-storage
          persistentVolumeClaim:
            claimName: media-config-local-storage-claim
        - name: media-local-storage
          persistentVolumeClaim:
            claimName: media-local-storage-claim
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediavpn
  name: mediavpn
spec:
  ports:
    - name: bazarr
      port: 7676
      targetPort: 6767
    - name: sonarr
      port: 9898
      targetPort: 8989
    - name: jackett
      port: 9845
      targetPort: 9117
    - name: lidarr
      port: 8687
      targetPort: 8686
    - name: qbit-web-ui
      port: 9078
      targetPort: 9078
    - name: qbit-tcp
      port: 7439
      targetPort: 6881
      protocol: TCP
    - name: qbit-udp
      port: 7439
      targetPort: 6881
      protocol: UDP
  selector:
    app: mediavpn