- name: Template Docker Compose and Env Files
  ansible.builtin.template:
    mode: u=rw,g=r
    src: "{{ item.src }}"
    dest: "~/{{ item.dest_name }}"
  loop: '{{ docker_template_files }}'

- name: Create Resources
  community.docker.docker_compose_v2:
    project_name: '{{ compose_project_name }}'
    project_src: "~/"
    files:
      - '{{ compose_file }}'

- name: Remove All Templated Files
  ansible.builtin.file:
    path: "~/{{ item.dest_name }}"
    state: absent
  loop: '{{ docker_template_files }}'
