- name: Ensure disk usage is under 85 percent
  ansible.builtin.debug:
    msg: "Disk usage for {{ item.mount }} is {{ (item.size_available / item.size_total) * 100 }}%"
  when: item.mount == "/" and (item.size_available / item.size_total) > 0.85
  failed_when: item.mount == "/" and (item.size_available / item.size_total) > 0.85
  loop: "{{ ansible_facts['mounts'] }}"

- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Clean repo
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Check if system reboot is required
  become: true
  ansible.builtin.stat:
    path: /run/reboot-required
  register: reboot_required

################ If Automatic Reboot is Allowed #####################

- name: Send Reboot Starting Message to Slack
  community.general.slack:
    token: '{{ slack_token }}'
    color: warning
    msg: 'The server {{ inventory_hostname }} will be rebooting.'
  when: reboot_required.stat.exists and allow_automatic_reboot

- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: reboot_required.stat.exists and allow_automatic_reboot

- name: Send Reboot Finished Message to Slack
  community.general.slack:
    token: '{{ slack_token }}'
    color: good
    msg: 'The server {{ inventory_hostname }} has finished rebooting.'
  when: reboot_required.stat.exists and allow_automatic_reboot

########################################################################


################ If Automatic Reboot is Not Allowed ####################

- name: Notify that Reboot Needs to Occur
  community.general.slack:
    token: '{{ slack_token }}'
    color: warning
    msg: 'The server {{ inventory_hostname }} needs to be rebooted.'
  when: reboot_required.stat.exists and not allow_automatic_reboot
