- name: Ensure disk usage is under 85 percent
  ansible.builtin.debug:
    msg: "Disk usage for {{ item.mount }} is {{ (item.size_available / item.size_total) * 100 }}%"
  when: item.mount == "/" and (item.size_available / item.size_total) > 0.85
  failed_when: item.mount == "/" and (item.size_available / item.size_total) > 0.85
  loop: "{{ ansible_facts['mounts'] }}"

- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Clean repo
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
