---
- name: Template compose file
  ansible.builtin.template:
    mode: u=rw,g=r
    src: pi.compose.j2
    dest: ~/pi.compose


# Pihole should be setup on debian https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu
- name: Create PiHole
  become_user: "{{ ansible_user }}"
  community.docker.docker_compose:
    project_name: DNS_Pihole
    project_src: "~/"
    files:
      - "pi.compose"

- name: Delete template file
  ansible.builtin.file:
    state: absent
    path: "~/pi.compose"

