---
# Pihole should be setup on debian https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu

- name: Create PiHole Resource
  vars:
    docker_template_files:
      - src: pi.compose.j2
        dest_name: pi.compose
    compose_file: pi.compose
    compose_project_name: pihole
  ansible.builtin.include_tasks: ../tasks/docker-compose-up.yml
