http:
 #region routers 
  routers:
    # Tools
    
    nextcloud:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.homelab.ezequielvalencia.com`)"
      middlewares:
        - default-headers
      tls: {}
      service: nextcloud
    

#endregion
#region services
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
        passHostHeader: true
    

#endregion
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
        - default-headers