- name: Ensure disk usage is under 85 percent
  ansible.builtin.debug:
    msg: "Disk usage for {{ item.mount }} is {{ (item.size_available / item.size_total) * 100 }}%"
  when: item.mount == "/" and (item.size_available / item.size_total) > 0.85
  failed_when: item.mount == "/" and (item.size_available / item.size_total) > 0.85
  loop: "{{ ansible_facts['mounts'] }}"

- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Clean repo
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Check if system reboot is required
  become: true
  ansible.builtin.stat:
    path: /run/reboot-required
  register: reboot_required

################ If Automatic Reboot is Allowed #####################

- name: Starting Reboot
  vars:
    slack_color: "#fff305"
    slack_title: "{{ inventory_hostname }} Will Begin Rebooting"
    slack_text: ""
    slack_priority: "Low"
  ansible.builtin.include_tasks: send-slack-message.yml
  when: reboot_required.stat.exists and allow_automatic_reboot

- name: Reboot machine
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: reboot_required.stat.exists and allow_automatic_reboot

- name: Finished Reboot
  vars:
    slack_color: "#0505ff"
    slack_title: "{{ inventory_hostname }} Finished Rebooting"
    slack_text: ""
    slack_priority: "Low"
  ansible.builtin.include_tasks: send-slack-message.yml
  when: reboot_required.stat.exists and allow_automatic_reboot

########################################################################


################ If Automatic Reboot is Not Allowed ####################

- name: Need To Reboot
  vars:
    slack_color: "#fff305"
    slack_title: "{{ inventory_hostname }} Needs To Reboot"
    slack_text: ""
    slack_priority: "Medium"
  ansible.builtin.include_tasks: send-slack-message.yml
  when: reboot_required.stat.exists and not allow_automatic_reboot
