apiVersion: v1
kind: PersistentVolume
metadata:
  name: MediaLocalStorage
spec:
  capacity:
    storage: 700Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  hostPath:
    path: # Example host path to simulate an empty directory
    type: DirectoryOrCreate


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: MediaLocalStorageClaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 700Gi
  volumeName: MediaLocalStorage

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: MediaConfigLocalStorage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  hostPath:
    path: # Example host path to simulate an empty directory
    type: DirectoryOrCreate


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: MediaConfigLocalStorageClaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 10Gi
  volumeName: MediaConfigLocalStorage

