- name: Create Photoprisim
  community.docker.docker_container:
    name: Photoprisim
    image: photoprism/photoprism


- name: Create Vaultwarden
  community.docker.docker_container:
    name: Vaultwarden
    image: vaultwarden/server
    recreate: true
    state: started
    restart_policy: always
    published_ports:
      - "9730:443"

- name: Create Trillium
  community.docker.docker_container:
    name: Trillium

- name: Create Firefly
  community.docker.docker_container:
    name: Firefly
