---
- name: Init home lab
  hosts: ubuntu_server
  gather_facts: false
  vars:
    refused_ssh: "port 22: Connection refused"
    alt_ssh_port: 5320

  pre_tasks:
    - name: Check ssh port
      ansible.builtin.ping:
      ignore_unreachable: true
      register: ssh_result

    - name: Set ssh port if not 22
      ansible.builtin.set_fact:
        ansible_port: "{{ alt_ssh_port }}"
      when: ssh_result.msg is defined and refused_ssh in ssh_result.msg

    - name: Gather facts now
      ansible.builtin.gather_facts:

    - name: Check for python env
      ansible.builtin.stat:
        path: '{{ ansible_env.HOME }}/pyvenv/bin/python3'
      register: pythonvenv_status

    - name: Set python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: '{{ ansible_env.HOME }}/pyvenv/bin/python3'
      when: pythonvenv_status.stat.exists

  tasks:
    - name: Startup Ubuntu
      when: "ansible_facts['os_family'] | lower == 'debian'"
      ansible.builtin.include_role:
        name: debian-system-startup

    - name: Install low-sensitiviy applications
      when: inventory_hostname in groups['low_server']
      ansible.builtin.include_role:
        name: "low-sensitivity"


    - name: Install infrastructure Applications
      when: inventory_hostname in groups['infra_server']
      ansible.builtin.include_role:
        name: infra

    - name: Install sus applications
      when: inventory_hostname in groups['media_server']
      ansible.builtin.include_role:
        name: media_install

    - name: Install sensitive applications
      when: inventory_hostname in groups['sensitive_server']
      ansible.builtin.include_role:
        name: firefly_install
