---
- name: Check Servers
  hosts: "ubuntu_server"
  gather_facts: false
  vars:
    refused_ssh: "port 22: Connection refused"
    alt_ssh_port: 5320

  tasks:

  - name: Check ssh port
    ansible.builtin.ping:
    ignore_unreachable: true
    register: ssh_result

  - name: Set ssh port if not 22
    ansible.builtin.set_fact:
      ansible_port: "{{ alt_ssh_port }}"
    when: ssh_result.msg is defined and refused_ssh in ssh_result.msg

  - name: Gather facts now
    ansible.builtin.gather_facts:

  - name: Ping Server
    ansible.builtin.ping:
