
packages:
  - vim

security_ssh_port: "{{ alt_ssh_port }}"
security_ssh_allowed_groups:
  - admin
security_sudoers_passworded:
  - "{{ owner_user }}"
  - ansible

security_ssh_allowed_users:
  - "{{ owner_user }}"
  - ansible

security_autoupdate_enabled: false

# Defaults
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"

security_sshd_state: started
security_ssh_restart_handler_state: restarted

security_sudoers_passwordless: []

security_autoupdate_blacklist: []
security_autoupdate_reboot: false
security_autoupdate_reboot_time: "03:00" # 24hr time frame

security_autoupdate_mail_to: ""
security_autoupdate_mail_on_error: true

security_fail2ban_enabled: true
security_fail2ban_custom_configuration_template: "jail.local.j2"
