http:
 #region routers 
  routers:

    # Admin
    ### Proxmox
    zimaprox:
      entryPoints:
        - "https"
      rule: "Host(`zimaprox.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: zimaprox
    pcprox:
      entryPoints:
        - "https"
      rule: "Host(`pcprox.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pcprox
    laptopprox:
      entryPoints:
        - "https"
      rule: "Host(`laptopprox.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: laptopprox
    
    ### Other
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - redirectregex-pihole
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: truenas
    

    # Tools
    
    nextcloud:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: nextcloud
    firefly:
      entryPoints:
        - "https"
      rule: "Host(`firefly.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: firefly
    dashy:
      entryPoints:
        - "https"
      rule: "Host(`dashy.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: dashy
    

    # Media
    jellyfin:
      entryPoints:
        - "https"
      rule: "Host(`jellyfin.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: jellyfin
    sonarr:
      entryPoints:
        - "https"
      rule: "Host(`sonarr.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: sonarr
    radarr:
      entryPoints:
        - "https"
      rule: "Host(`radarr.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: radarr
    lidarr:
      entryPoints:
        - "https"
      rule: "Host(`lidarr.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lidarr
    bazarr:
      entryPoints:
        - "https"
      rule: "Host(`bazarr.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: bazarr
    qbit:
      entryPoints:
        - "https"
      rule: "Host(`qbit.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: qbit
    jackett:
      entryPoints:
        - "https"
      rule: "Host(`jackett.homelab.ezequielvalencia.com`)"
      middlewares:
        - authelia
        - default-headers
        - https-redirectscheme
      tls: {}
      service: jackett

#endregion
#region services
  services:

    # Admin
    zimaprox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.3:8006"
        passHostHeader: true
    laptopprox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.4:8006"
        passHostHeader: true
    pcprox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.5:8006"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.0.6:80"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "https://10.0.0.13"
        passHostHeader: true
    
    # Tools
    firefly:
      loadBalancer:
        servers:
          - url: "http://10.0.0.10:5780"
        passHostHeader: true
    nextcloud:
      loadBalancer:
        servers:
          - url: "https://10.0.0.13:9782"
        passHostHeader: true
    dashy:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:8080"
        passHostHeader: true
    
    # Media
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:7260"
        passHostHeader: true
    sonarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:9898"
        passHostHeader: true
    lidarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:8687"
        passHostHeader: true
    radarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:8787"
        passHostHeader: true
    jackett:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:9845"
        passHostHeader: true
    bazarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:7676"
        passHostHeader: true
    qbit:
      loadBalancer:
        servers:
          - url: "http://10.0.0.7:9078"
        passHostHeader: true

#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.homelab.ezequielvalencia.com"

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/24"
        # - "192.168.0.0/16"
        # - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers