---

- name: Include Variables
  ansible.builtin.include_vars:
    dir: vars
    extensions:
      - "yml"


########################
## Dependency Install ##
########################

- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Clean repo
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Install Vim
  become: true
  ansible.builtin.apt:
    pkg: vim
    state: present

- name: Install QEMU Guest Agent
  become: true
  ansible.builtin.apt:
    pkg: qemu-guest-agent
    state: present
  when: is_qemu_guest

- name: Install PythonVenv
  become: true
  ansible.builtin.apt:
    name:
      - python3-virtualenv

- name: Create Venv
  ansible.builtin.pip:
    virtualenv: '/home/{{ ansible_user }}/pyvenv'
    name:
      - docker==6.1.2
      - docker-compose
      - pyyaml==5.3.1

- name: Switch to New Python interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: '{{ ansible_env.HOME }}/pyvenv/bin/python3'
  when: not pythonvenv_status.stat.exists

- name: Geerlinguy Docker Install
  ansible.builtin.include_role:
    name: geerlingguy.docker
    apply:
      become: true


####################
## Base Sec       ##
####################
# Would use OSAP for security, but its automated ansible scripts maybe a pain to implement
- name: Geerling Security
  ansible.builtin.include_role:
    # https://github.com/geerlingguy/ansible-role-security
    name: geerlingguy.security
    apply:
      become: true


- name: Restart sshd for Debian
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: ansible_facts['distribution'] == "Debian"

## If Ubuntu its ssh not sshd
- name: Restart ssh for Ubuntu
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Ensure the configured SSH port is used for remainder of role
  ansible.builtin.set_fact:
    ansible_port: "{{ alt_ssh_port }}"


###################
## Misc          ##
###################


- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: debian
