---
- name: Init home lab
  hosts: ubuntu_server
  gather_facts: false
  vars:
    refused_ssh: "port 22: Connection refused"
    alt_ssh_port: 5320

  tasks:
    - name: Check ssh port
      ansible.builtin.ping:
      ignore_unreachable: true
      register: ssh_result

    - name: Set ssh port if not 22
      ansible.builtin.set_fact:
        ansible_port: "{{ alt_ssh_port }}"
      when: ssh_result.msg is defined and refused_ssh in ssh_result.msg

    - name: Gather facts now
      ansible.builtin.gather_facts:

    - name: Startup Ubuntu
      ansible.builtin.include_role:
        name: ubuntu-system-startup
      when: "ansible_facts['distribution'] | lower == 'ubuntu'"

    - name: Install low-sensitiviy applications
      ansible.builtin.include_role:
        name: "low-sensitivity"
      when: inventory_hostname in groups['low_server']

    - name: Install infrastructure Applications
      ansible.builtin.include_role:
        name: infra
      when: inventory_hostname in groups['infra_server']

    - name: Install sus applications
      ansible.builtin.include_role:
        name: sus-applications
      when: inventory_hostname in groups['sus_server']

    - name: Install sensitive applications
      ansible.builtin.include_role:
        name: sensitive-applications
      when: inventory_hostname in groups['sensitive_server']

    # Reset only if the ssh has not been changed already
    - name: Restart ssh daemon
      become: true
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: ssh_result.msg is defined and refused_ssh not in ssh_result.msg
