---
- name: Package Management
  hosts: "ubuntu_server"
  become: true # sets them to become a super user
  tasks:
    # tasks to do as the super user
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    - name: Install docker prequisuites
      ansible.builtin.apt:
        state: present
        pkg:
          - apt-transport-https
          - curl
          - gnupg
          - ca-certificates

    - name: Add GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository to apt
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu lunar stable
        state: present

    - name: Install docker
      ansible.builtin.apt:
        state: present
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Add user to docker group
      ansible.builtin.user:
        user: "{{ ansible_user }}"
        group: docker

    - name: Check docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: "Create Portainer container"
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        restart_policy: always
        recreate: true
        published_ports:
          - "8000:8000"
          - "9789:9443"
        volumes:
          - portainer_data:/data/portainer-ce
          - /var/run/docker.sock:/var/run/docker.sock
