---
- name: Update packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Clean repo
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Install essential packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present

####################
## Base Sec       ##
####################
# Would use OSAP for security, but its automated ansible scripts maybe a pain to implement
- name: Geerling Security
  ansible.builtin.include_role:
    # https://github.com/geerlingguy/ansible-role-security
    name: geerlingguy.security
    apply:
      become: true

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

