
authelia_volume_folder: '{{ defualt_relative_docker_data_path }}/authelia'

authelia_template_files:
  - src: authelia.compose.j2
    dst: /home/ansible/authelia.compose
  
  - src: config.yml.j2
    dst: '{{ authelia_volume_folder }}/configuration.yml'

authelia_internal_alias: authelia